fail_fast: false
repos:
  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-format
        args: [--style=file, "-i"]
      - id: clang-tidy
        args: ["--quiet", "--extra-arg", "--std=c++2c", "--checks=cppcoreguidelines*"]
      - id: cppcheck
        args: ["--project=build/compile_commands.json", --library=boost, "-DBOOST_FIXTURE_TEST_SUITE(x, y)=", "-DBOOST_AUTO_TEST_SUITE_END()="]
      - id: cpplint
        args: ["--filter=-whitespace,-legal,-build/include_order,-runtime/references,-build/include_subdir,-build/c++11"]