name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
        - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run:
            mkdir docs/html -p
      - uses: DenverCoder1/doxygen-github-pages-action@v1.3.0
        with:
          github_token:
          branch: gh-pages
          folder: docs/html
          config_file: Doxyfile