name: SonarQube Scan

on:
  push:
    branches:
      - master

jobs:
  sonarqube-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Install build-wrapper
      run: |
        # Download and install build-wrapper
        curl -L https://sonarcloud.io/static/cpp/build-wrapper-linux-x86.zip -o build-wrapper.zip
        unzip build-wrapper.zip
        chmod +x build-wrapper-linux-x86/build-wrapper
        sudo mv build-wrapper-linux-x86 /usr/local/bin/build-wrapper

    - name: Set reusable strings
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: CMake with coverage enable
      run: |
        cmake -B ${{ steps.strings.outputs.build-output-dir }} -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON

    - name: Build
      run: |
        build-wrapper-linux-x86-64 --out-dir bw-output cmake --build ${{ steps.strings.outputs.build-output-dir }} . --target install -- -j ${NUMBER_OF_PROCESSORS}

    - name: Run tests
      run: |
        ctest

    - name: SonarQube Scan
      run: |
        # Your SonarQube scan command here
        sonar-scanner \
          -Dsonar.projectKey=Vixen \
          -Dsonar.organization=pallasz88 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.cfamily.build-wrapper-output=build-wrapper-output \
          -Dsonar.cfamily.gcov.reportsPath=${{ steps.strings.outputs.build-output-dir }}
